language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: pypi
  user: cnheider
  password:
    secure: nKe9AgQFKCo4GbAT+TQnEhonFPv7jFm/IHQK6LTOh9Yi9fYiVtoZtaspFNy45pp9slcnMAzTZV5iBui/EGvV2ZMzbtUYJ7TqgRTyHkE3rmLY9cqbGQR7+klYpqJyo7oCOVCm+f2dyyuF/20H0BgShvxSuq5EhxqglWnIKJEMAT78yY+AIJ5TN3k+/5+WIFhyJbv5T9+IBhxZkNU7aik25hhRCVfvaCkNIjP0WmTgwX5Fu48o3K1pGOElYYlaYAvzBfn96ehBnJJbbyWLuylS5w0DOvRpF1xinf97Mv3QEYHueyWR8gtuWdyoLYTtLKLPs1wzEY3vWLB4hLkStmgYHFRCLWCgb87W4CXrA9TVIEW0H7mTIrk2vfzkABaJdYZ+t77F9QqmrTtB/Fa7RfGXY1PQA/UAySkhuXK3DuFgQ/RCDs4dySQAbtxoTU1d3ezB2Ny9c1Sw15XSBoLnX4Ruv3z0iFTg/ch4zhLhaSOiuJ2VwuPKgT04B78fDoF0d7baQ8DbaUMKYlVvVEIq9tvIT93fb/5un2BIyIS2qM+wCBzjwXuLsoio87eOplChAvP5ocpcj8ORd+d2/RNS935/0gzdsLjnzD5rKK4vZZBatdfo+hDc82QwBEN3vL2l6CxImC8RqeYSOa1/3n2DJ0KJOfUQ3QT1PLIcPbKeBpxBc/0=
